config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  resources :questions do
    resources :answers, only: %i[create destroy update], shallow: true do
      member do
        patch :set_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :rating_up
      patch :rating_down
      patch :cancel_vote
    end
  end

  resources :attachments, only: :destroy
  resources :questions, :answers, concerns: [:votable] do
    resources :comments, only: %i[create destroy update], shallow: true
  end

  get :set_authorization_confirmed, to: 'authorizations#set_confirmed'

  get :search, to: 'search#search'

  namespace :users do
    get :set_email
    post :create_user
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  belongs_to :user

  validates :body, :title, presence: true, length: { minimum: 5 }

  default_scope { order(updated_at: :desc) }

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attr| attr['file'].blank? }

  after_create :subscribe_author

  def has_best_answer?
    answers.best.exists?
  end

  def best_answer
    answers.best.first
  end

  private

  def subscribe_author
    subscriptions.create!(user: self.user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question, serializer: SeparateQuestionSerializer
  end

  def create
    respond_with(question = current_resource_owner.questions.create(question_params))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, only: %i[show update destroy]
  before_action :gon_question_author, only: :show
  before_action :build_answer, only: :show
  before_action :find_subscription, only: :show
  after_action :publish_question, only: :create

  respond_to :js, only: :update
  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def gon_question_author
    gon.question_author_id = @question.user_id
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def find_subscription
    @subscription = @question.subscriptions.where(user: current_user).first
  end

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
.nested-fields
  = f.label :file
  |
  = link_to_remove_association (octicon 'dash', height: 32,
                        class: 'text-danger minus-file'), f
  br
  = f.file_field :file

app/views/questions/_edit_form.html.slim
= form_for @question, remote: true do |f|
    p
      = f.label :title
      br
      = f.text_field :title, id: :question_title
    p
      = f.label :body
      br
      = f.text_area :body, id: :question_body, rows: 6, cols: 50
    b Attachments:
    .attachments
      = f.fields_for :attachments do |attachment|
        = render 'attachment_fields', f: attachment
    .links
      = render 'shared/link_attachments', f: f
    p= f.submit 'Update question', class: 'btn btn-outline-info'

app/views/questions/_form.html.slim
= form_with model: @question do |f|
  = render 'shared/errors', resource: @question
  p
    = f.label :title
    br
    = f.text_field :title, id: :question_title
  p
    = f.label :body
    br
    = f.text_area :body, id: :question_body, rows: 6, cols: 50
  b Attachments:
  .attachments
    = f.fields_for :attachments, @question.attachments.build do |attachment|
      = render 'attachment_fields', f: attachment
  .links
    = render 'shared/link_attachments', f: f
    p= f.submit 'Create', class: 'btn btn-lg btn-outline-info'

app/views/questions/_question.html.slim
p
  = link_to question.title, question_path(question)
  br
  = truncate(question.body, length: 75)

app/views/questions/_question_more.html.slim
- if @question.persisted?
  .question
    - cache_unless current_user.try(:admin), ["question_info", @question] do
      h1= @question.title
      .
        .info
          i= "Author: #{author(@question)}"
          br
          span= "asked #{created_date(@question)}"
    .
      - if current_user && @subscription.nil?
        i= link_to 'Subscribe to question', question_subscriptions_path(@question), method: :post
      - if @subscription
        i= link_to 'Unsubscribe', subscription_path(@subscription), method: :delete
    - if can? :update, @question
      => link_to 'hide', '', class: "btn btn-warning hide-link hide-question-link", data: { question_id: @question.id }
      => link_to 'Edit question', '', class: 'edit-question-link btn btn-info'
      = link_to 'Delete question', question_path(@question), class: 'btn btn-danger', method: :delete
      .question-update-errors
      = render 'edit_form'
    hr
    - cache_unless current_user.try(:admin), ["question_rating", @question] do
      div class="question_rating rating"
        = @question.rating
    - if can? :rating_up, @question
      = render 'shared/rating_links', resource: @question
    = render 'shared/cancel_vote', resource: @question
    div class="vote_error_question"
    - cache_unless current_user.try(:admin), ["question_body", @question] do
      = @question.body
    br
    - if @question.attachments.present?
      .attachments_question
        b Attachments:
        ul
          = render @question.attachments, cache: true
    - if can? :create, Comment
      => link_to 'hide', '', class: "hide-link hide-add-comment-link hide-comment-form_question_#{@question.id}", data: { resource_id: @question.id, resource_type: "question" }
      = link_to 'add a comment', '', class: "add-comment-link add-comment-link_question_#{@question.id}", data: { resource_id: @question.id, resource_type: "question" }
      br
      div id="comment-errors-question-#{@question.id}"
      = render 'comments/form', commentable: @question
    hr
    div class="question_#{@question.id}_comments comments"
      = render @question.comments, cache: true
  hr

app/views/questions/index.html.slim
- if can? :create, Question
  p
    =link_to 'Ask question', new_question_path, class: "btn btn-info btn-lg new_question"
h1= 'Questions list'
br
.questions_list
  - cache @questions do
    = render @questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
= render 'question_more', cache: true
br
h2 Answers
hr
div class="answers" data-question-id="#{@question.id}"
  = render @question.answers, cache: true
- if user_signed_in?
  .answers-errors
  = render 'answers/form'

app/views/questions/update.js.erb
<% if @question&.errors.present? %>
  $('.question-update-errors').html("<%= j render 'shared/errors', resource: @question %>");
<% else %>
  $('.question').html('<%= j render 'question_more' %>').removeClass('question');
<% end %>