config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  resources :questions do
    resources :answers, only: %i[create destroy update], shallow: true do
      member do
        patch :set_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :rating_up
      patch :rating_down
      patch :cancel_vote
    end
  end

  resources :attachments, only: :destroy
  resources :questions, :answers, concerns: [:votable] do
    resources :comments, only: %i[create destroy update], shallow: true
  end

  get :set_authorization_confirmed, to: 'authorizations#set_confirmed'

  get :search, to: 'search#search'

  namespace :users do
    get :set_email
    post :create_user
  end

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, optional: true, touch: true

  validates :body, presence: true, length: { minimum: 5 }
  after_create :publish_comment

  default_scope { order(updated_at: :asc)}

  private

  def publish_comment
    question_id = commentable.is_a?(Question) ? commentable_id : commentable.question.id

    ActionCable.server.broadcast(
      "question:#{question_id}:comments",
        { comment: self.to_json(include: :user) } )
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_commentable, only: :create
  before_action :set_comment, only: %i[update destroy]

  respond_to :js
  authorize_resource

  def create
    respond_with(@comment = @commentable.comments.create(comment_params.merge(user: current_user)))
  end

  def update
    @comment.update(comment_params)
    @commentable = @comment.commentable
    respond_with @comment
  end

  def destroy
    respond_with(@comment.destroy)
  end

  private

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        @commentable = $1.classify.constantize.find(value)
      end
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/views/comments/_comment.html.slim
- if comment.persisted?
  div class="comment_#{comment.id} comment"
    - cache comment do
      = comment.body
      span.text-primary= " - #{author(comment)}"
      span.text-secondary= " #{created_date(comment)}"
      br
    - if can? :destroy, comment
      => link_to 'hide', '', class: "hide-link hide-comment-link hide-comment_#{comment.id}-form", data: { comment_id: comment.id }
      => link_to 'edit comment', '', class: "edit-comment-link edit-comment_#{comment.id}-link", data: { comment_id: comment.id }
      |   |
      =< link_to 'delete comment', comment_path(comment), class: 'delete-comment-link', method: :delete, remote: true, data: { confirm: 'Are you sure?' }
      div id="comment-update-errors-#{comment.id}"
      = form_for comment, remote: true do |f|
        = f.label :body, 'Comment'
        br
        = f.text_area :body, id: :comment_body
        br
        = f.submit 'Update', class: 'btn btn-outline-info'
        end
  hr

app/views/comments/_form.html.slim
= form_for [commentable, commentable.comments.build], html: { id: "new_comment_#{commentable.class.name.underscore}_#{commentable.id}" }, remote: true do |f|
  p
    = f.label :body
    br
    = f.text_area :body, id: :create_comment_body, rows: 6, cols: 50
  p= f.submit 'Comment', class: 'btn btn-lg btn-outline-info'

app/views/comments/create.js.erb
var errors_field = $('#comment-errors-<%= @comment.commentable_type.underscore %>-<%= @commentable.id %>')

<% if @comment&.errors.present? %>
  errors_field.html("<%= j render 'shared/errors', resource: @comment %>");
<% else %>
  $('.<%= @comment.commentable_type.underscore %>_<%= @commentable.id %>_comments').append('<%= j render @comment %>');
  $('#new_comment_<%= @comment.commentable_type.underscore %>_<%= @commentable.id %>').hide()
  errors_field.hide()
<% end %>

app/views/comments/destroy.js.erb
$('.comment_<%= @comment.id %>').remove();

app/views/comments/update.js.erb
<% if @comment&.errors.present? %>
  $('#comment-update-errors-<%= @comment.id %>').html("<%= j render 'shared/errors', resource: @comment %>");
<% else %>
  $('.comment_<%= @comment.id %>').html('<%= j render @comment %>').removeClass("comment");
<% end %>