config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  resources :questions do
    resources :answers, only: %i[create destroy update], shallow: true do
      member do
        patch :set_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :rating_up
      patch :rating_down
      patch :cancel_vote
    end
  end

  resources :attachments, only: :destroy
  resources :questions, :answers, concerns: [:votable] do
    resources :comments, only: %i[create destroy update], shallow: true
  end

  get :set_authorization_confirmed, to: 'authorizations#set_confirmed'

  get :search, to: 'search#search'

  namespace :users do
    get :set_email
    post :create_user
  end

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!

  def search
    authorize! :do, :search
    search = Search.new(search_params)

    if search.valid?
      @search_body = search_params[:search_body]
      @search_object = search_params[:search_object]
      @results = search.search_handler
    else
      redirect_to root_path
    end
  end

  private

  def search_params
    params.permit(:search_body, :search_object)
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def search_options
    Search::SEARCH_OPTIONS.map { |option| [option, option] }
  end

  def results_handler(result)
    type = result.class.name

    case type
    when "User"
      tag.b("User:") + result.username
    when "Question"
      tag.div((link_to result.title, question_path(result)) + tag.br + result.body.truncate(40))
    else
      tag.b(type) + tag.br + result.body.truncate(40)
    end
  end

  def search_cache(object, body, results)
    size = results.size
    max_updated_at = results.max_by(&:updated_at).updated_at.try(:utc).try(:to_s)
    "#{object}/#{body}-#{size}-#{max_updated_at}"
  end

end

app/views/search/_form.html.slim
= form_tag search_path, class: 'form-inline my-2 my-lg-0 search', method: :get do |f|
  => text_field_tag :search_body, "", class: "form-control mr-sm-2", placeholder: 'Search...'
  => select_tag :search_object, options_for_select(search_options, "all"), class: 'custom-select'
  | &nbsp;
  =< submit_tag 'Search', class: 'btn btn-outline-info', name: nil

app/views/search/execute.html.slim
b Search results:
- @results.each do |result|
  .result
    =results_handler(result)

app/views/search/search.html.slim
h3 Search results:
- cache search_cache(@search_object, @search_body, @results) do
  - @results.each do |result|
    .result
      =results_handler(result)
    hr