config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  resources :questions do
    resources :answers, only: %i[create destroy update], shallow: true do
      member do
        patch :set_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :rating_up
      patch :rating_down
      patch :cancel_vote
    end
  end

  resources :attachments, only: :destroy
  resources :questions, :answers, concerns: [:votable] do
    resources :comments, only: %i[create destroy update], shallow: true
  end

  get :set_authorization_confirmed, to: 'authorizations#set_confirmed'

  get :search, to: 'search#search'

  namespace :users do
    get :set_email
    post :create_user
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, presence: true, length: { minimum: 5 }

  after_create :publish_answer
  after_create :send_to_subscribers

  default_scope { order(best: :desc, created_at: :asc) }
  scope :best, -> { where(best: true) }

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attr| attr['file'].blank? }

  def set_best!
    Answer.transaction do
      question.best_answer.update!(best: false) if question.has_best_answer?
      self.update!(best: true)
    end
  end

  private

  def publish_answer
    ActionCable.server.broadcast(
      "question:#{question_id}:answers",
        { answer: self.to_json(include: %i[user attachments]) }
    )
  end

  def send_to_subscribers
    NewAnswerEmailDistributionJob.perform_later(self.question, self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :find_question, only: :create
  before_action :set_answer, only: %i[destroy update set_best]

  respond_to :js
  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def set_best
    @question = @answer.question
    @answer.set_best!
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_answer, only: :show
  before_action :find_question, only: %i[index create]
  authorize_resource

  def index
    respond_with(@question.answers)
  end

  def show
    respond_with @answer, serializer: SeparateAnswerSerializer
  end

  def create
    respond_with(@question.answers.create(answer_params.merge(user: current_resource_owner)))
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def show_set_best?(user, answer)
    user&.author_of?(answer.question) && !answer.best?
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div class='answer_#{answer.id} answer'
    - cache_unless current_user.try(:admin), [ "answer_info", answer ] do
      - if answer.best?
        = octicon 'check', height: 32, class: 'text-success'
      .info
        i= "Author: #{author(answer)}"
        br
        span= "answered #{created_date(answer)}"
      div class="answer_#{answer.id}_rating rating"
        = answer.rating
    - if can? :rating_up, answer
      = render 'shared/rating_links', resource: answer
    = render 'shared/cancel_vote', resource: answer
      div class="vote_error_#{answer.id}"
    - cache_unless current_user.try(:admin), ["answer_body", answer] do
      => answer.body
    br
    - if answer.attachments.present?
      div class="attachments_answer_#{answer.id}"
        b Attachments:
        ul
          = render answer.attachments, cache: true
    - if can? :set_best, answer
      = link_to 'Set best', set_best_answer_path(answer), method: :patch, class: 'best-answer-link', data: { answer_id: answer.id }, remote: true
      br
    - if can? :destroy, answer
      p
        => link_to 'hide', '', class: "hide-link hide-answer-link hide-answer_#{answer.id}-form", data: { answer_id: answer.id }
        => link_to 'edit', '', class: "edit-answer-link edit-answer_#{answer.id}-link", data: { answer_id: answer.id }
        |   |
        =< link_to 'delete answer', answer_path(answer), class: 'delete-answer-link', method: :delete, remote: true, data: { confirm: 'Are you sure?' }
      p
        div id='answer-update-errors-#{answer.id}'
        = render 'answers/edit_form', answer: answer
    - if can? :create, Comment
      => link_to 'hide', '', class: "hide-link hide-add-comment-link hide-comment-form_answer_#{answer.id}", data: { resource_id: answer.id, resource_type: "answer" }
      = link_to 'add a comment', '', class: "add-comment-link add-comment-link_answer_#{answer.id}", data: { resource_id: answer.id, resource_type: "answer" }
      br
      div id="comment-errors-answer-#{answer.id}"
      = render 'comments/form', commentable: answer
    div class="answer_#{answer.id}_comments comments"
      b Comments:
      = render answer.comments, cache: true
  hr

app/views/answers/_attachment_fields.html.slim
.nested-fields
  = f.label :file
  br
  = f.file_field :file
  = link_to_remove_association (octicon 'dash', height: 32, class: 'text-danger'), f

app/views/answers/_edit_form.html.slim
= form_for answer, remote: true do |f|
  = f.label :body, 'Answer'
  br
  = f.text_area :body, id: :answer_body
  br
  b Attachments:
  .attachments
    = f.fields_for :attachments, answer.attachments.build do |attachment|
      = render 'attachment_fields', f: attachment
  .links
    = render 'shared/link_attachments', f: f
  = f.submit 'Update answer', class: 'btn btn-outline-info'

app/views/answers/_form.html.slim
.new-answer-form
  b Your answer:
  = form_with model: [@question, @answer], remote: true do |f|
    p
      = f.label :body, ''
      br
      = f.text_area :body, id: :create_answer_body, rows: 6, cols: 50
      br
      b Attachments:
      div class="attachments_add_answer"
        = f.fields_for :attachments, @answer.attachments.build do |attachment|
          = render 'attachment_fields', f: attachment
      .links
        = link_to_add_association (octicon 'plus', height: 32, class: 'text-success'), f, :attachments, data: { association_insertion_node: '.attachments_add_answer', association_insertion_method: :append }
    p= f.submit 'Answer', class: 'btn btn-lg btn-outline-info'

app/views/answers/choose_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
$('.answers-errors').html("<%= j render 'shared/errors', resource: @answer %>");
$('.answers').append('<%= j render @answer %>');
$('#create_answer_body').val('');

app/views/answers/destroy.js.erb
$('.answer_<%= @answer.id %>').remove();

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
<% if @answer&.errors.present? %>
  $('#answer-update-errors-<%= @answer.id %>').html("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answer_<%= @answer.id %>').html('<%= j render @answer %>').removeClass("answer");
<% end %>